from django.urls import path
from . import views
urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('student/login/', views.student_login, name='student_login'),
    path('student/logout/', views.student_logout_view, name='student_logout'),
    path('student/dashboard/', views.student_self_dashboard, name='student_self_dashboard'),
    path('student/mark/<int:session_pk>/', views.student_mark_self, name='student_mark_self'),
    path('labs/', views.lab_list, name='lab_list'),
    path('labs/add/', views.lab_create, name='lab_create'),
    path('labs/<int:pk>/edit/', views.lab_edit, name='lab_edit'),
    path('labs/<int:pk>/delete/', views.lab_delete, name='lab_delete'),
    path('students/', views.student_list, name='student_list'),
    path('students/add/', views.student_create, name='student_create'),
    path('students/<int:pk>/', views.student_detail, name='student_detail'),
    path('students/<int:pk>/edit/', views.student_edit, name='student_edit'),
    path('students/<int:pk>/delete/', views.student_delete, name='student_delete'),
    path('sessions/', views.session_list, name='session_list'),
    path('sessions/new/', views.session_create, name='session_create'),
    path('sessions/<int:pk>/', views.session_detail, name='session_detail'),
    path('sessions/<int:pk>/mark/', views.mark_attendance, name='mark_attendance'),
    path('sessions/<int:pk>/toggle/', views.session_toggle_active, name='session_toggle_active'),
    path('sessions/<int:pk>/delete/', views.session_delete, name='session_delete'),
    path('sessions/<int:pk>/export/', views.export_csv, name='export_csv'),
    path('holidays/', views.holiday_list, name='holiday_list'),
    path('holidays/add/', views.holiday_create, name='holiday_create'),
    path('holidays/<int:pk>/delete/', views.holiday_delete, name='holiday_delete'),
    path('reports/', views.reports, name='reports'),
    path('ajax/update-record/', views.ajax_update_record, name='ajax_update_record'),
]
